"use client";
import { useState, useEffect } from 'react';
import { createClient } from '@/lib/supabase';
import { useRouter } from 'next/navigation';
import jsPDF from 'jspdf';

interface ChecklistItem {
  id: string;
  title: string;
  description: string;
  completed: boolean;
  article: string;
}

export default function DashboardPage() {
  const [user, setUser] = useState<any>(null);
  const [riskScore, setRiskScore] = useState<number>(0);
  const [loading, setLoading] = useState(true);
  const [checklist, setChecklist] = useState<ChecklistItem[]>([
    {
      id: '1',
      title: 'AI 시스템 등록',
      description: '고위험 AI 시스템을 MSIT에 등록하세요',
      completed: false,
      article: '제32조',
    },
    {
      id: '2',
      title: '개인정보 처리 동의',
      description: 'PIPC 요구사항에 따른 사용자 동의 확보',
      completed: false,
      article: '제33조',
    },
    {
      id: '3',
      title: '감사 로그 시스템',
      description: '모든 AI 추론에 대한 감사 로그 구현',
      completed: false,
      article: '제34조',
    },
    {
      id: '4',
      title: '투명성 보고서',
      description: 'AI 시스템 작동 방식에 대한 투명성 문서 작성',
      completed: false,
      article: '제35조',
    },
    {
      id: '5',
      title: '데이터 거버넌스',
      description: '데이터 품질 및 보안 관리 체계 구축',
      completed: false,
      article: '제36조',
    },
  ]);
  const router = useRouter();
  const supabase = createClient();

  useEffect(() => {
    checkUser();
  }, []);

  const checkUser = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        router.push('/login');
        return;
      }

      setUser(user);
      
      // Load user's risk score and checklist progress
      await loadUserData(user.id);
    } catch (error) {
      console.error('Error checking user:', error);
      router.push('/login');
    } finally {
      setLoading(false);
    }
  };

  const loadUserData = async (userId: string) => {
    try {
      // Try to fetch user data from Supabase
      const { data: userData, error } = await supabase
        .from('user_profiles')
        .select('risk_score, checklist_progress')
        .eq('user_id', userId)
        .single();

      if (userData && !error) {
        setRiskScore(userData.risk_score || 0);
        if (userData.checklist_progress) {
          setChecklist(userData.checklist_progress);
        }
      } else {
        // If no data exists, use defaults and create profile
        await createUserProfile(userId);
      }
    } catch (error) {
      console.error('Error loading user data:', error);
    }
  };

  const createUserProfile = async (userId: string) => {
    try {
      await supabase.from('user_profiles').insert({
        user_id: userId,
        risk_score: 0,
        checklist_progress: checklist,
      });
    } catch (error) {
      console.error('Error creating user profile:', error);
    }
  };

  const toggleChecklistItem = async (itemId: string) => {
    const updatedChecklist = checklist.map(item =>
      item.id === itemId ? { ...item, completed: !item.completed } : item
    );
    setChecklist(updatedChecklist);

    // Save to Supabase
    if (user) {
      try {
        await supabase
          .from('user_profiles')
          .upsert({
            user_id: user.id,
            checklist_progress: updatedChecklist,
          });
      } catch (error) {
        console.error('Error saving checklist progress:', error);
      }
    }
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    
    // Title
    doc.setFontSize(20);
    doc.text('AI Compliance Report', 20, 20);
    doc.text('AI 준법 보고서', 20, 30);
    
    // Company info
    doc.setFontSize(12);
    doc.text(`Company: ${user?.user_metadata?.company_name || 'N/A'}`, 20, 45);
    doc.text(`Email: ${user?.email || 'N/A'}`, 20, 52);
    doc.text(`Date: ${new Date().toLocaleDateString('ko-KR')}`, 20, 59);
    
    // Risk Score
    doc.setFontSize(16);
    doc.text('Risk Score (위험도 점수)', 20, 75);
    doc.setFontSize(24);
    doc.text(`${riskScore}/100`, 20, 85);
    
    // Compliance Checklist
    doc.setFontSize(16);
    doc.text('Compliance Checklist (준법 체크리스트)', 20, 105);
    
    doc.setFontSize(10);
    let yPos = 115;
    checklist.forEach((item, index) => {
      const status = item.completed ? '✓ Completed' : '○ Pending';
      doc.text(`${index + 1}. ${item.title} - ${status}`, 25, yPos);
      doc.text(`   ${item.description}`, 25, yPos + 5);
      doc.text(`   Article: ${item.article}`, 25, yPos + 10);
      yPos += 20;
    });
    
    // Footer
    doc.setFontSize(8);
    doc.text('Generated by AI Compliance Guardian', 20, 280);
    doc.text('© 2025 AI 준법 가디언. All rights reserved.', 20, 285);
    
    // Save PDF
    doc.save('AI_Compliance_Report.pdf');
  };

  const handleLogout = async () => {
    await supabase.auth.signOut();
    router.push('/login');
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 via-white to-red-50">
        <div className="text-2xl font-bold text-blue-600">로딩 중...</div>
      </div>
    );
  }

  const completedItems = checklist.filter(item => item.completed).length;
  const progressPercentage = (completedItems / checklist.length) * 100;

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-red-50">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-lg border-b-2 border-blue-200 shadow-lg">
        <div className="container mx-auto px-4 py-4">
          <div className="flex justify-between items-center">
            <h1 className="text-2xl font-black text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-blue-800">
              🇰🇷 AI 준법 가디언
            </h1>
            <div className="flex items-center gap-4">
              <span className="text-sm text-gray-600">
                {user?.user_metadata?.company_name || user?.email}
              </span>
              <button
                onClick={handleLogout}
                className="px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white rounded-lg text-sm font-semibold transition-all"
              >
                로그아웃
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <div className="container mx-auto px-4 py-8">
        <div className="grid md:grid-cols-3 gap-6 mb-8">
          {/* Risk Score Card */}
          <div className="bg-white/80 backdrop-blur-lg rounded-2xl shadow-xl p-6 border-2 border-blue-200">
            <h2 className="text-lg font-bold text-gray-700 mb-4">위험도 점수</h2>
            <div className="text-center">
              <div className="text-5xl font-black text-blue-600 mb-2">{riskScore}</div>
              <div className="text-sm text-gray-600">/ 100</div>
              <div className="mt-4">
                {riskScore < 30 && (
                  <span className="inline-block px-3 py-1 bg-green-100 text-green-700 rounded-full text-sm font-semibold">
                    저위험
                  </span>
                )}
                {riskScore >= 30 && riskScore < 70 && (
                  <span className="inline-block px-3 py-1 bg-yellow-100 text-yellow-700 rounded-full text-sm font-semibold">
                    중위험
                  </span>
                )}
                {riskScore >= 70 && (
                  <span className="inline-block px-3 py-1 bg-red-100 text-red-700 rounded-full text-sm font-semibold">
                    고위험
                  </span>
                )}
              </div>
            </div>
          </div>

          {/* Progress Card */}
          <div className="bg-white/80 backdrop-blur-lg rounded-2xl shadow-xl p-6 border-2 border-blue-200">
            <h2 className="text-lg font-bold text-gray-700 mb-4">준법 진행률</h2>
            <div className="text-center">
              <div className="text-5xl font-black text-blue-600 mb-2">{Math.round(progressPercentage)}%</div>
              <div className="text-sm text-gray-600 mb-4">
                {completedItems} / {checklist.length} 완료
              </div>
              <div className="w-full bg-gray-200 rounded-full h-4">
                <div
                  className="bg-gradient-to-r from-blue-600 to-blue-800 h-4 rounded-full transition-all"
                  style={{ width: `${progressPercentage}%` }}
                />
              </div>
            </div>
          </div>

          {/* Deadline Card */}
          <div className="bg-white/80 backdrop-blur-lg rounded-2xl shadow-xl p-6 border-2 border-red-200">
            <h2 className="text-lg font-bold text-gray-700 mb-4">⏰ 시행까지</h2>
            <div className="text-center">
              <div className="text-5xl font-black text-red-600 mb-2">437</div>
              <div className="text-sm text-gray-600">일 남음</div>
              <div className="mt-4 text-xs text-gray-500">
                2026년 1월 22일
              </div>
            </div>
          </div>
        </div>

        {/* Compliance Checklist */}
        <div className="bg-white/80 backdrop-blur-lg rounded-2xl shadow-xl p-8 border-2 border-blue-200 mb-8">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-black text-gray-800">준법 체크리스트</h2>
            <button
              onClick={generatePDF}
              className="px-6 py-2 bg-gradient-to-r from-blue-600 to-blue-800 hover:from-blue-700 hover:to-blue-900 text-white font-bold rounded-lg shadow-lg hover:shadow-xl transition-all"
            >
              📄 PDF 다운로드
            </button>
          </div>

          <div className="space-y-4">
            {checklist.map((item) => (
              <div
                key={item.id}
                className={`p-4 rounded-xl border-2 transition-all cursor-pointer ${
                  item.completed
                    ? 'bg-green-50 border-green-300'
                    : 'bg-white border-gray-200 hover:border-blue-300'
                }`}
                onClick={() => toggleChecklistItem(item.id)}
              >
                <div className="flex items-start gap-4">
                  <div className="flex-shrink-0 mt-1">
                    <div
                      className={`w-6 h-6 rounded-full border-2 flex items-center justify-center ${
                        item.completed
                          ? 'bg-green-500 border-green-500'
                          : 'border-gray-300'
                      }`}
                    >
                      {item.completed && (
                        <svg className="w-4 h-4 text-white" fill="currentColor" viewBox="0 0 20 20">
                          <path
                            fillRule="evenodd"
                            d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                            clipRule="evenodd"
                          />
                        </svg>
                      )}
                    </div>
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <h3 className={`font-bold ${item.completed ? 'text-green-700' : 'text-gray-800'}`}>
                        {item.title}
                      </h3>
                      <span className="px-2 py-1 bg-blue-100 text-blue-700 text-xs rounded-full font-semibold">
                        {item.article}
                      </span>
                    </div>
                    <p className="text-sm text-gray-600">{item.description}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Quick Actions */}
        <div className="grid md:grid-cols-3 gap-6">
          <div className="bg-white/80 backdrop-blur-lg rounded-2xl shadow-xl p-6 border-2 border-blue-200">
            <h3 className="text-lg font-bold text-gray-800 mb-4">📊 새로운 위험도 평가</h3>
            <p className="text-sm text-gray-600 mb-4">
              AI 시스템이 변경되었나요? 새로운 위험도 평가를 받아보세요.
            </p>
            <button
              onClick={() => router.push('/')}
              className="w-full px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition-all"
            >
              평가 시작하기
            </button>
          </div>

          <div className="bg-white/80 backdrop-blur-lg rounded-2xl shadow-xl p-6 border-2 border-blue-200">
            <h3 className="text-lg font-bold text-gray-800 mb-4">📚 준법 가이드</h3>
            <p className="text-sm text-gray-600 mb-4">
              한국 AI 기본법에 대한 상세한 가이드를 확인하세요.
            </p>
            <button
              onClick={() => router.push('/regulations')}
              className="w-full px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white font-semibold rounded-lg transition-all"
            >
              가이드 보기
            </button>
          </div>

          <div className="bg-white/80 backdrop-blur-lg rounded-2xl shadow-xl p-6 border-2 border-green-200">
            <h3 className="text-lg font-bold text-gray-800 mb-4">💬 피드백 보내기</h3>
            <p className="text-sm text-gray-600 mb-4">
              제품 개선을 위한 귀하의 의견을 공유해주세요.
            </p>
            <button
              onClick={() => router.push('/feedback')}
              className="w-full px-4 py-2 bg-green-600 hover:bg-green-700 text-white font-semibold rounded-lg transition-all"
            >
              피드백 제출
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
